export const STORE = {
  name: "EuroSuprise",
  logoText: "ES",
  slogan: "Европейские сладости и напитки с быстрой доставкой по городу",
  addressText: "Грозный, ул. Маяковского, 28",
  mapsUrl:
    "https://www.google.com/maps/search/?api=1&query=Grozny%2C%20ul.%20Mayakovskogo%2028",
  instagramUrl: "https://instagram.com/eurosuprise",
  phone: "+7 999 000 00 00",
  whatsappPhone: "+79280873332",
  telegramUsername: "eurosuprise",
  telegramLink: "https://t.me/eurosuprise",
  deliveryText: "Доставка по городу от 35 минут. Точное время подтверждаем в чате.",
  minDeliveryOrder: 1200,
  pickupReadyText: "Самовывоз обычно готов за 15-25 минут.",
  paymentText: "Оплата при получении: наличными или переводом.",
  workHours: {
    0: { open: null, close: null, closed: true },
    1: { open: "09:30", close: "22:00", closed: false },
    2: { open: "09:30", close: "22:00", closed: false },
    3: { open: "09:30", close: "22:00", closed: false },
    4: { open: "09:30", close: "22:00", closed: false },
    5: { open: "09:30", close: "23:00", closed: false },
    6: { open: "10:00", close: "23:00", closed: false },
  },
};

export const AVAIL = {
  IN_STOCK: "in_stock",
  LOW: "low",
  OUT: "out",
};

export const CATEGORIES = [
  { id: "new", name: "Новинки" },
  { id: "hits", name: "Хиты" },
  { id: "chocolate", name: "Шоколад" },
  { id: "marmalade", name: "Мармелад и жевательные" },
  { id: "kinder", name: "Kinder" },
  { id: "haribo", name: "Haribo" },
  { id: "cookies", name: "Печенье и вафли" },
  { id: "candies", name: "Батончики и драже" },
  { id: "drinks", name: "Напитки" },
  { id: "bundles", name: "Подарочные наборы" },
];

export const PRODUCTS = [
  {
    id: "p1",
    name: "Haribo Goldbears 100 г",
    price: 199,
    categoryId: "haribo",
    availability: AVAIL.IN_STOCK,
    description: "Классические фруктовые мишки Haribo. Универсальный выбор для детей и взрослых.",
    tags: ["кислое", "Германия"],
    image:
      "/img/catalog/official/p1.png",
    isNew: true,
    isHit: true,
    brand: "Haribo",
  },
  {
    id: "p2",
    name: "Haribo Happy Cola 100 г",
    price: 209,
    categoryId: "haribo",
    availability: AVAIL.IN_STOCK,
    description: "Жевательные мармеладки в форме мини-колы, с фирменным вкусом.",
    tags: ["мармелад", "Германия"],
    image:
      "/img/catalog/official/p2.png",
    isNew: false,
    isHit: true,
    brand: "Haribo",
  },
  {
    id: "p3",
    name: "Trolli Sour Brite Crawlers 120 г",
    price: 239,
    categoryId: "marmalade",
    availability: AVAIL.IN_STOCK,
    description: "Кисло-сладкие червячки Trolli с яркими фруктовыми вкусами.",
    tags: ["кислое", "США"],
    image:
      "/img/catalog/official/p3.png",
    isNew: false,
    isHit: false,
    brand: "Trolli",
  },
  {
    id: "p4",
    name: "Hanuta 44 г",
    price: 159,
    categoryId: "kinder",
    availability: AVAIL.LOW,
    description: "Хрустящая вафля с ореховой начинкой и слоем молочного шоколада.",
    tags: ["Италия"],
    image: "/img/catalog/official/p4.png",
    isNew: false,
    isHit: true,
    brand: "Kinder",
  },
  {
    id: "p5",
    name: "Kinder Bueno 2x43 г",
    price: 229,
    categoryId: "kinder",
    availability: AVAIL.IN_STOCK,
    description: "Тонкая вафля, нежный крем и молочный шоколад. Хит для быстрого перекуса.",
    tags: ["вафли", "Италия"],
    image:
      "/img/catalog/official/p5.png",
    isNew: false,
    isHit: true,
    brand: "Kinder",
  },
  {
    id: "p6",
    name: "Kinder Chocolate 8 батончиков",
    price: 289,
    categoryId: "kinder",
    availability: AVAIL.IN_STOCK,
    description: "Нежный молочный шоколад с молочной начинкой, классическая версия.",
    tags: ["молочный", "Италия"],
    image:
      "/img/catalog/official/p6.png",
    isNew: true,
    isHit: false,
    brand: "Kinder",
  },
  {
    id: "p7",
    name: "Milka Alpine Milk 100 г",
    price: 189,
    categoryId: "chocolate",
    availability: AVAIL.IN_STOCK,
    description: "Мягкий молочный шоколад из альпийского молока.",
    tags: ["классика", "Германия"],
    image:
      "/img/catalog/official/p7.png",
    isNew: false,
    isHit: false,
    brand: "Milka",
  },
  {
    id: "p8",
    name: "Ritter Sport Marzipan 100 г",
    price: 229,
    categoryId: "chocolate",
    availability: AVAIL.IN_STOCK,
    description: "Темный шоколад с мягкой марципановой начинкой.",
    tags: ["марципан", "Германия"],
    image:
      "/img/catalog/official/p8.webp",
    isNew: false,
    isHit: true,
    brand: "Ritter Sport",
  },
  {
    id: "p9",
    name: "Ritter Sport Cornflakes 100 г",
    price: 229,
    categoryId: "chocolate",
    availability: AVAIL.LOW,
    description: "Хрустящие кукурузные хлопья в молочном шоколаде.",
    tags: ["хруст", "Германия"],
    image:
      "/img/catalog/official/p9.jpg",
    isNew: false,
    isHit: false,
    brand: "Ritter Sport",
  },
  {
    id: "p10",
    name: "Nutella B-ready 6 шт",
    price: 299,
    categoryId: "cookies",
    availability: AVAIL.IN_STOCK,
    description: "Хрустящие палочки с нежной начинкой Nutella.",
    tags: ["орех", "Италия"],
    image:
      "/img/catalog/official/p10.png",
    isNew: false,
    isHit: true,
    brand: "Nutella",
  },
  {
    id: "p11",
    name: "Oreo Golden 154 г",
    price: 219,
    categoryId: "cookies",
    availability: AVAIL.IN_STOCK,
    description: "Ванильное печенье Oreo с кремовой начинкой.",
    tags: ["печенье", "США"],
    image:
      "/img/catalog/official/p11.png",
    isNew: true,
    isHit: false,
    brand: "Oreo",
  },
  {
    id: "p12",
    name: "Lotus Biscoff 250 г",
    price: 349,
    categoryId: "cookies",
    availability: AVAIL.IN_STOCK,
    description: "Карамельное печенье с насыщенным вкусом корицы.",
    tags: ["карамель", "Бельгия"],
    image:
      "/img/catalog/official/p12.png",
    isNew: false,
    isHit: true,
    brand: "Lotus",
  },
  {
    id: "p13",
    name: "Loacker Quadratini Vanilla 125 г",
    price: 269,
    categoryId: "cookies",
    availability: AVAIL.LOW,
    description: "Мини-вафли с ванильным кремом в удобной упаковке.",
    tags: ["вафли", "Италия"],
    image:
      "/img/catalog/official/p13.png",
    isNew: false,
    isHit: false,
    brand: "Loacker",
  },
  {
    id: "p14",
    name: "Skittles Fruits 136 г",
    price: 179,
    categoryId: "candies",
    availability: AVAIL.IN_STOCK,
    description: "Фруктовое драже с хрустящей оболочкой.",
    tags: ["драже", "США"],
    image:
      "/img/catalog/official/p14.jpg",
    isNew: false,
    isHit: true,
    brand: "Skittles",
  },
  {
    id: "p15",
    name: "M&M's Peanut 90 г",
    price: 189,
    categoryId: "candies",
    availability: AVAIL.IN_STOCK,
    description: "Шоколадное драже с цельным арахисом.",
    tags: ["арахис", "США"],
    image:
      "/img/catalog/official/p15.png",
    isNew: false,
    isHit: false,
    brand: "M&M's",
  },
  {
    id: "p16",
    name: "Twix White 46 г",
    price: 129,
    categoryId: "candies",
    availability: AVAIL.IN_STOCK,
    description: "Батончик с карамелью и печеньем в белом шоколаде.",
    tags: ["батончик", "Европа"],
    image:
      "/img/catalog/official/p16.png",
    isNew: true,
    isHit: false,
    brand: "Twix",
  },
  {
    id: "p17",
    name: "Coca-Cola Cherry Import 0.33 л",
    price: 169,
    categoryId: "drinks",
    availability: AVAIL.IN_STOCK,
    description: "Газированный напиток с вишневым вкусом в импортной версии.",
    tags: ["0.33л", "вишня"],
    image: "/img/catalog/official/p17.jpg",
    isNew: true,
    isHit: true,
    brand: "Coca-Cola",
  },
  {
    id: "p18",
    name: "Fanta Exotic 0.33 л",
    price: 169,
    categoryId: "drinks",
    availability: AVAIL.IN_STOCK,
    description: "Фанта с тропическими нотами и ярким ароматом.",
    tags: ["0.33л", "тропики"],
    image:
      "/img/catalog/official/p18.png",
    isNew: false,
    isHit: false,
    brand: "Fanta",
  },
  {
    id: "p19",
    name: "Dr Pepper Vanilla Float 0.355 л",
    price: 219,
    categoryId: "drinks",
    availability: AVAIL.LOW,
    description: "Газировка с ароматом ванильного десерта.",
    tags: ["0.355л", "США"],
    image:
      "/img/catalog/official/p19.png",
    isNew: false,
    isHit: true,
    brand: "Dr Pepper",
  },
  {
    id: "p20",
    name: "Toblerone Milk 100 г",
    price: 259,
    categoryId: "chocolate",
    availability: AVAIL.IN_STOCK,
    description: "Знаменитый треугольный шоколад с медом и миндалем.",
    tags: ["Швейцария", "мед"],
    image:
      "/img/catalog/official/p20.png",
    isNew: true,
    isHit: false,
    brand: "Toblerone",
  },
];

export const BUNDLES = [
  {
    id: "b1",
    name: "Weekend Mini Box",
    price: 1490,
    categoryId: "bundles",
    availability: AVAIL.IN_STOCK,
    description:
      "Компактный набор для двоих: сладости, вафли и 2 напитка.",
    composition:
      "— Шоколад 2 шт\n— Мармелад 2 шт\n— Печенье 1 шт\n— Напиток 2 шт",
    image:
      "/img/catalog/official/p10.png",
    isNew: false,
    isHit: true,
    brand: "EuroSuprise",
    tags: ["на двоих", "подарок"],
  },
  {
    id: "b2",
    name: "Family Mix Box",
    price: 2990,
    categoryId: "bundles",
    availability: AVAIL.LOW,
    description:
      "Расширенный семейный набор + мини-сюрприз внутри.",
    composition:
      "— Шоколад 4 шт\n— Мармелад 4 шт\n— Kinder 3 шт\n— Печенье 3 шт\n— Напиток 3 шт",
    image:
      "/img/catalog/official/p7.png",
    isNew: false,
    isHit: false,
    brand: "EuroSuprise",
    tags: ["семейный", "выгодно"],
  },
  {
    id: "b3",
    name: "Premium Celebration",
    price: 4990,
    categoryId: "bundles",
    availability: AVAIL.IN_STOCK,
    description: "Премиальный набор для праздника и больших компаний.",
    composition:
      "— Шоколад 7 шт\n— Мармелад 5 шт\n— Kinder 4 шт\n— Печенье 4 шт\n— Напитки 4 шт",
    image:
      "/img/catalog/official/p20.png",
    isNew: true,
    isHit: true,
    brand: "EuroSuprise",
    tags: ["премиум", "праздник"],
  },
  {
    id: "b4",
    name: "Sweet Office Pack",
    price: 3790,
    categoryId: "bundles",
    availability: AVAIL.IN_STOCK,
    description:
      "Набор в офис: ассортимент сладостей и напитков на команду.",
    composition:
      "— Шоколад 6 шт\n— Мармелад 5 шт\n— Печенье 4 шт\n— Напитки 5 шт",
    image: "/img/catalog/official/p14.jpg",
    isNew: true,
    isHit: false,
    brand: "EuroSuprise",
    tags: ["офис", "на компанию"],
  },
];

export const CART_KEY = "mvp_cart";
export const ORDERS_KEY = "mvp_orders";
export const FAVORITES_KEY = "mvp_favorites";
